apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebookmgmt-rent
  labels:
    app: ebookmgmt-rent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebookmgmt-rent
  template:
    metadata:
      labels:
        app: ebookmgmt-rent
    spec:
      containers:
        - name: ebookmgmt-rent
          image: username/ebookmgmt-rent:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5